// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onRgbChange();
void onPowerChange();
void onHumidityChange();
void onLdrChange();
void onTempChange();

String rgb;
CloudSwitch power;
int humidity;
int ldr;
int temp;

void initProperties(){

  ArduinoCloud.addProperty(rgb, READWRITE, ON_CHANGE, onRgbChange);
  ArduinoCloud.addProperty(power, READWRITE, ON_CHANGE, onPowerChange);
  ArduinoCloud.addProperty(humidity, READWRITE, ON_CHANGE, onHumidityChange, 1000);
  ArduinoCloud.addProperty(ldr, READWRITE, ON_CHANGE, onLdrChange, 255);
  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange, 1000);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
